version: "3.7"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./nginx-proxy.conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - "metacritic_api"
    networks:
      - back-tier

  metacritic_api:
    build: ./
    image: metacritic_api
    container_name: metacritic_api
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      URL: "http://www.metacritic.com/game/playstation-4"
    networks:
      - back-tier

networks:
  back-tier:
